name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  http: any
  dio: ^3.0.4
  scoped_model: ^1.0.1
  flutter_localizations:
    sdk: flutter
  provider: ^3.1.0+1
  fluwx: ^1.1.3
  share: ^0.6.2+1
  android_intent: 0.3.0
  local_auth: any
  qrscan: ^0.2.17
  qr_flutter: ^3.2.0
  flutter_easyrefresh: ^2.0.8
  flutter_staggered_grid_view: ^0.3.0
  flutter_custom_clippers: ^1.1.0
#  permission_handler: ^4.0.0
  image_gallery_saver : ^1.1.0
  flutter_cache_manager: any
  like_button: any
#  sharesdk_plugin: 1.1.7
#  flute_music_player: any #播放器
#  audioplayers: any
  rxdart: ^0.20.0
  path_provider: ^1.5.1
  jpush_flutter: 0.1.0
#  flutter_app_badger: any
  flutter_map: any # or the latest version on Pub
  jverify:
    git:
      url: git://github.com/jpush/jverify-flutter-plugin.git
      ref: dev
  canknow_flutter_ui:
    path: G:\project\canknow\canknow_flutter_ui
#    git:
#      url: https://e.coding.net/canknow/canknow_flutter_ui.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - locale/
    - assets/icons/
    - assets/images/emotions/default/
    - assets/images/emotions/figure/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
